services:
  db:
    image: postgres:15-alpine
    container_name: declared_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: local_dev_password_123
      POSTGRES_DB: declared_system
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
